inherit_mode:
  merge:
    - exclude
    - include

require:
  - ./outdated_software_test.rb
  - ./sensitive_info_check.rb
  - ./sql_injection_check.rb

Custom/OutdatedPackageCheck:
  Enabled: true

Custom/SensitiveInfoExposure:
  Enabled: true
  MaxPermissions: 0600  # Permissions maximales autorisées (en octal)
  SensitiveFilenamePatterns:
    - 'secret*'
    - 'password*'
    - 'credential*'
    - '*.key'
    - '*.pem'
    - '*.crt'
    - '*.env*'
    - '*config*'

Custom/CodeInjectionRisk:
  Enabled: true
  Include:
    - '**/*.rb'
    - '**/*.py'
    - '**/*.sql'
    - '**/*.sh'

Style/RedundantSelfAssignmentBranch:
  Enabled: true

Layout/EndOfLine:
  Enabled: false

AllCops:
  NewCops: enable
